# Generated by Django 3.1.6 on 2021-04-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='pfp',
            field=models.CharField(max_length=250),
        ),
    ]
